Step 1:Import libraries

In [1]:
import pandas as pd
import numpy as np

Step 2:Load the dataset

In [2]:
df = pd.read_csv('yektanet.csv', encoding='utf8')
df.tail()

,keywords,segments,visit count
219614,"['نتایج زنده', 'نتایج', 'زنده']","['maleSegment', 'varzeshi']",641
219615,"['زیرنویس', 'فارسی فیلم', 'دانلود زیرنویس']",['femaleSegment'],355
219616,"['سامان', 'ساعت']",['femaleSegment'],40
219617,"['چشم', 'تنظیم', 'رنگ', 'نرم']",['technology'],523
219618,"['خارجی', 'قوی', 'ایرانی خارجی', 'ایرانی']",['femaleSegment'],906

Step 3: We group the data by the keywords and count how many times each keyword appears in the dataset.
This helps us undrestand which keywords are more frequent.

In [3]:
grouped = df.groupby('keywords')
keyword_counts = grouped['keywords'].apply(len).reset_index(name='count')
keyword_counts.head()

                         keywords  count
0      ['øªø', 'øªù', 'ø²', 'ùˆ']     38
1             ['øªø', 'ø²', 'ùˆ']      3
2  ['øªø', 'ø¹ø ùˆ', 'ø¹ø', 'ùˆ']      2
3                  ['øªø', 'ø¹ø']      1
4                   ['øªø', 'ùˆ']      1

Step 4: Filter frequent keywords

In [4]:
filtered_df = keyword_counts[keyword_counts['count'] > 1400]
filtered_df

                                                keywords  count
32244                    ['صفحه اخبار', 'صفحه', 'اخبار']   9103
44549          ['نتایج زنده', 'فوتبال', 'نتایج', 'زنده']   2565
44551                    ['نتایج زنده', 'نتایج', 'زنده']   9644
46124     ['نی', 'تبادل', 'نی سایت', 'نی نی', 'موضوعات']   1435
46212  ['نی', 'نظرهای نی', 'تبادل نظرهای', 'نظرهای', ...   1500

Step 5: Calculated the popularity column

We create a new column called 'popularity' by dividing each rows 'visit count' by the total 'visit count' of its keyword group.

In [8]:
df['popularity'] = df['visit count'] / df.groupby('keywords')['visit count'].transform('sum') * 100
df['popularity'] = df['popularity'].round(2)

In [9]:
df

,keywords,segments,visit count,popularity
0,"['باران', 'پروفایل']","['khanevadehvakhanedari', 'salamat', 'moosighi...",127,100.00
1,"['نتایج زنده', 'نتایج', 'زنده']",['maleSegment'],822,0.02
2,"['معنی فارسی', 'معنی', 'فارسی', 'فارسی معنی']",['femaleSegment'],726,10.34
3,"['نتایج زنده', 'نتایج', 'زنده']",['maleSegment'],307,0.01
4,"['نتایج زنده', 'نتایج', 'زنده']",['maleSegment'],778,0.02
...,...,...,...,...
219614,"['نتایج زنده', 'نتایج', 'زنده']","['maleSegment', 'varzeshi']",641,0.01
219615,"['زیرنویس', 'فارسی فیلم', 'دانلود زیرنویس']",['femaleSegment'],355,1.09
219616,"['سامان', 'ساعت']",['femaleSegment'],40,2.69
219617,"['چشم', 'تنظیم', 'رنگ', 'نرم']",['technology'],523,40.89
219618,"['خارجی', 'قوی', 'ایرانی خارجی', 'ایرانی']",['femaleSegment'],906,100.00